### ISSUE TITLE
Don't work on Fork CMS 5.5.2

### ISSUE THREAD

**Issue by Sellato** [sumocoders/fork-slideshows#12]
Don't work on Fork CMS 5.5.2

When I try to "Add slide", I got this error after push the "add button"

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY sequence asc' at line 4`

`Uncaught PHP Exception PDOException: "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY sequence asc' at line 4" at vendor/spoon/library/spoon/database/database.php line 662`

![p2](https://user-images.githubusercontent.com/5456419/60385346-e0438400-9a90-11e9-85b4-7c2f62d08a75.jpg)

**Comment by carakas** [comment]
@Sellato I fixed it. if you download the module again it should work

**Comment by Sellato** [comment]
:)

Thanks
